/**
 * RAG store + retrieval library.
 *
 * Writes go through raw SQL because Prisma does not natively support the
 * `vector` column type (schema uses `Unsupported("vector(1536)")`).
 *
 * Scope enforcement lives in the SQL WHERE clause, never in JavaScript
 * post-filtering — this is a hard guardrail against engagement bleed-through.
 */
import { randomBytes } from "crypto";

import { Prisma } from "@/generated/prisma/client";
import { prisma } from "@/lib/db";

import { embed, embedBatch } from "./embedder";

// ─── Types ──────────────────────────────────────────────────────────────────

export type ChatScope = "ENGAGEMENT" | "ADMIN";

export interface IndexArtefactParams {
  engagementId?: string;
  sourceType: string;
  sourceId: string;
  content: string;
  metadata?: Record<string, unknown>;
}

export interface IndexStructuredRowParams {
  engagementId?: string;
  sourceType: string;
  sourceId: string;
  summary: string;
  metadata?: Record<string, unknown>;
}

export interface SimilaritySearchParams {
  queryEmbedding: number[];
  scope: ChatScope;
  engagementId?: string;
  topK?: number;
}

export interface SimilaritySearchHit {
  id: string;
  content: string;
  metadata: Record<string, unknown> | null;
  sourceType: string;
  sourceId: string;
  engagementId: string | null;
  score: number;
}

// ─── Chunking ───────────────────────────────────────────────────────────────

/**
 * Paragraph-aware chunker. Breaks on `\n\n` preferentially, then falls back
 * to hard character slicing. `overlapChars` characters from the end of the
 * previous chunk are prepended to the next chunk for context continuity.
 */
export function chunkText(
  text: string,
  maxChars = 500,
  overlapChars = 100
): string[] {
  const normalized = text.replace(/\r\n/g, "\n").trim();
  if (normalized.length === 0) return [];
  if (normalized.length <= maxChars) return [normalized];

  const paragraphs = normalized
    .split(/\n{2,}/)
    .map((p) => p.trim())
    .filter((p) => p.length > 0);

  const chunks: string[] = [];
  let current = "";

  for (const para of paragraphs) {
    // Paragraph itself is larger than maxChars — hard-split it first.
    if (para.length > maxChars) {
      if (current.length > 0) {
        chunks.push(current);
        current = "";
      }
      let offset = 0;
      while (offset < para.length) {
        const slice = para.slice(offset, offset + maxChars);
        chunks.push(slice);
        offset += maxChars - overlapChars;
        if (offset <= 0) offset = maxChars; // guard against weird overlap configs
      }
      continue;
    }

    const candidate = current.length === 0 ? para : `${current}\n\n${para}`;
    if (candidate.length <= maxChars) {
      current = candidate;
    } else {
      if (current.length > 0) chunks.push(current);
      current = para;
    }
  }
  if (current.length > 0) chunks.push(current);

  if (overlapChars <= 0 || chunks.length <= 1) return chunks;

  // Apply overlap: prepend the tail of the previous chunk to each subsequent chunk.
  const withOverlap: string[] = [chunks[0]];
  for (let i = 1; i < chunks.length; i++) {
    const prev = chunks[i - 1];
    const tail = prev.slice(Math.max(0, prev.length - overlapChars));
    withOverlap.push(`${tail}\n\n${chunks[i]}`);
  }
  return withOverlap;
}

// ─── Vector helpers ─────────────────────────────────────────────────────────

/**
 * pgvector accepts a literal of the form `[0.1,0.2,...]`. We cast it with
 * `::vector` at the SQL site. Values are always plain numbers generated by
 * OpenAI — no user-controlled data ends up here.
 */
function toVectorLiteral(vec: number[]): string {
  return `[${vec.map((n) => (Number.isFinite(n) ? n : 0)).join(",")}]`;
}

function cuid(): string {
  // Mirror Prisma's @default(cuid()) shape loosely — just enough to be unique.
  // 25-char random id prefixed with `c` to visually distinguish from UUIDs.
  return `c${randomBytes(12).toString("hex")}`;
}

// ─── Writers ────────────────────────────────────────────────────────────────

/**
 * Delete all chunks for a given (sourceType, sourceId) pair. Idempotent.
 * Used before re-indexing so we never accumulate stale rows.
 */
export async function deleteChunksFor(
  sourceType: string,
  sourceId: string
): Promise<number> {
  const result = await prisma.$executeRaw`
    DELETE FROM "EmbeddingChunk"
    WHERE "sourceType" = ${sourceType}
      AND "sourceId" = ${sourceId}
  `;
  return Number(result);
}

/**
 * Chunk a long artefact body, embed each chunk, and insert them atomically.
 * Deletes any prior chunks for the same source before inserting.
 * Returns the list of inserted chunk ids.
 */
export async function indexArtefact(
  params: IndexArtefactParams
): Promise<string[]> {
  const { engagementId, sourceType, sourceId, content, metadata } = params;
  const chunks = chunkText(content);
  if (chunks.length === 0) {
    await deleteChunksFor(sourceType, sourceId);
    return [];
  }

  const vectors = await embedBatch(chunks);
  const ids = chunks.map(() => cuid());
  const metadataJson = metadata ? JSON.stringify(metadata) : null;

  await prisma.$transaction(async (tx) => {
    await tx.$executeRaw`
      DELETE FROM "EmbeddingChunk"
      WHERE "sourceType" = ${sourceType}
        AND "sourceId" = ${sourceId}
    `;

    for (let i = 0; i < chunks.length; i++) {
      const id = ids[i];
      const chunk = chunks[i];
      const vec = toVectorLiteral(vectors[i]);
      // Rough token estimate: 4 chars per token.
      const tokens = Math.ceil(chunk.length / 4);

      await tx.$executeRaw`
        INSERT INTO "EmbeddingChunk" (
          "id", "engagementId", "sourceType", "sourceId",
          "chunkIndex", "content", "embedding", "tokens", "metadata", "createdAt"
        ) VALUES (
          ${id},
          ${engagementId ?? null},
          ${sourceType},
          ${sourceId},
          ${i},
          ${chunk},
          ${vec}::vector,
          ${tokens},
          ${metadataJson === null ? Prisma.DbNull : Prisma.sql`${metadataJson}::jsonb`},
          NOW()
        )
      `;
    }
  });

  return ids;
}

/**
 * Single-chunk variant for short structured content (one TorRequirement,
 * LineItem, Assumption, RiskRegisterEntry, etc.). Overwrites any prior
 * chunk for the same source.
 */
export async function indexStructuredRow(
  params: IndexStructuredRowParams
): Promise<string> {
  const { engagementId, sourceType, sourceId, summary, metadata } = params;
  const trimmed = summary.trim();
  if (trimmed.length === 0) {
    await deleteChunksFor(sourceType, sourceId);
    return "";
  }

  const [vector] = await embedBatch([trimmed]);
  const id = cuid();
  const metadataJson = metadata ? JSON.stringify(metadata) : null;
  const vec = toVectorLiteral(vector);
  const tokens = Math.ceil(trimmed.length / 4);

  await prisma.$transaction(async (tx) => {
    await tx.$executeRaw`
      DELETE FROM "EmbeddingChunk"
      WHERE "sourceType" = ${sourceType}
        AND "sourceId" = ${sourceId}
    `;
    await tx.$executeRaw`
      INSERT INTO "EmbeddingChunk" (
        "id", "engagementId", "sourceType", "sourceId",
        "chunkIndex", "content", "embedding", "tokens", "metadata", "createdAt"
      ) VALUES (
        ${id},
        ${engagementId ?? null},
        ${sourceType},
        ${sourceId},
        ${0},
        ${trimmed},
        ${vec}::vector,
        ${tokens},
        ${metadataJson === null ? Prisma.DbNull : Prisma.sql`${metadataJson}::jsonb`},
        NOW()
      )
    `;
  });

  return id;
}

// ─── Retrieval ──────────────────────────────────────────────────────────────

interface SimilarityRow {
  id: string;
  content: string;
  metadata: unknown;
  sourceType: string;
  sourceId: string;
  engagementId: string | null;
  distance: number;
}

/**
 * Cosine-distance similarity search via pgvector's `<=>` operator.
 *
 * SCOPE ENFORCEMENT IS SQL-SIDE:
 *   - scope="ENGAGEMENT"  → WHERE "engagementId" = $engagementId
 *   - scope="ADMIN"       → no engagement filter (admin role is pre-checked
 *                           by the caller)
 *
 * The caller MUST be authorised before invoking this — the store does not
 * perform auth itself.
 */
export async function similaritySearch(
  params: SimilaritySearchParams
): Promise<SimilaritySearchHit[]> {
  const { queryEmbedding, scope, engagementId } = params;
  const topK = Math.max(1, Math.min(params.topK ?? 8, 50));

  if (queryEmbedding.length === 0) return [];

  if (scope === "ENGAGEMENT" && !engagementId) {
    throw new Error(
      "similaritySearch: engagementId is required when scope=ENGAGEMENT"
    );
  }

  const vec = toVectorLiteral(queryEmbedding);

  const rows: SimilarityRow[] =
    scope === "ENGAGEMENT"
      ? await prisma.$queryRaw<SimilarityRow[]>`
          SELECT
            "id",
            "content",
            "metadata",
            "sourceType",
            "sourceId",
            "engagementId",
            ("embedding" <=> ${vec}::vector) AS "distance"
          FROM "EmbeddingChunk"
          WHERE "engagementId" = ${engagementId}
          ORDER BY "embedding" <=> ${vec}::vector ASC
          LIMIT ${topK}
        `
      : await prisma.$queryRaw<SimilarityRow[]>`
          SELECT
            "id",
            "content",
            "metadata",
            "sourceType",
            "sourceId",
            "engagementId",
            ("embedding" <=> ${vec}::vector) AS "distance"
          FROM "EmbeddingChunk"
          ORDER BY "embedding" <=> ${vec}::vector ASC
          LIMIT ${topK}
        `;

  return rows.map((r) => ({
    id: r.id,
    content: r.content,
    metadata:
      r.metadata && typeof r.metadata === "object"
        ? (r.metadata as Record<string, unknown>)
        : null,
    sourceType: r.sourceType,
    sourceId: r.sourceId,
    engagementId: r.engagementId,
    // Cosine distance → similarity score in [0, 1]; higher is more similar.
    score: 1 - Number(r.distance),
  }));
}

// ─── Convenience: embed + search in one call ───────────────────────────────

export async function searchByText(
  text: string,
  scope: ChatScope,
  engagementId?: string,
  topK?: number
): Promise<SimilaritySearchHit[]> {
  const queryEmbedding = await embed(text);
  return similaritySearch({ queryEmbedding, scope, engagementId, topK });
}
