import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { listObjects } from "@/lib/storage";
import path from "path";

/**
 * Map phase numbers to the S3 directory prefixes they write to.
 * Files in these directories are considered "generated by" that phase.
 */
const PHASE_FILE_PREFIXES: Record<string, string[]> = {
  "0": ["research/"],
  "1": ["initial_questions/", "claude-artefacts/tor-assessment"],
  "1A": ["estimates/", "claude-artefacts/optimistic", "claude-artefacts/technical-proposal"],
  "2": ["responses_qna/", "claude-artefacts/response-analysis"],
  "3": ["estimates/", "claude-artefacts/estimate-review"],
  "3R": ["claude-artefacts/gap-analysis", "claude-artefacts/revised"],
  "5": ["claude-artefacts/technical-proposal"],
};

interface FileEntry {
  key: string;
  name: string;
  dir: string;
  ext: string;
}

export async function GET(
  _request: NextRequest,
  { params }: { params: Promise<{ id: string; phase: string }> }
) {
  const session = await auth();
  if (!session?.user?.id) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { id, phase } = await params;
  const prefixes = PHASE_FILE_PREFIXES[phase] ?? [];

  if (prefixes.length === 0) {
    return NextResponse.json({ files: [] });
  }

  const files: FileEntry[] = [];
  const seen = new Set<string>();

  for (const prefix of prefixes) {
    const fullPrefix = `engagements/${id}/${prefix}`;
    const keys = await listObjects(fullPrefix);

    for (const key of keys) {
      if (seen.has(key)) continue;
      seen.add(key);

      // Strip the engagement prefix to get relative path
      const relativePath = key.replace(`engagements/${id}/`, "");
      const name = path.basename(key);
      const dir = path.dirname(relativePath);
      const ext = path.extname(name).slice(1).toLowerCase();

      files.push({ key: relativePath, name, dir, ext });
    }
  }

  // Sort: directories first, then alphabetically
  files.sort((a, b) => {
    if (a.dir !== b.dir) return a.dir.localeCompare(b.dir);
    return a.name.localeCompare(b.name);
  });

  return NextResponse.json({ files });
}
