import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../src/generated/prisma/client";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter });

type BenchmarkSeed = {
  techStack: "DRUPAL" | "WORDPRESS" | "WORDPRESS_NEXTJS";
  category: string;
  taskType: string;
  lowHours: number;
  highHours: number;
  notes?: string;
};

const benchmarks: BenchmarkSeed[] = [
  // --- Drupal: Content Architecture ---
  {
    techStack: "DRUPAL",
    category: "Content Architecture",
    taskType: "Content type (simple, < 10 fields)",
    lowHours: 4,
    highHours: 8,
    notes: "Including form display, view modes",
  },
  {
    techStack: "DRUPAL",
    category: "Content Architecture",
    taskType: "Content type (complex, 10-25 fields)",
    lowHours: 8,
    highHours: 20,
    notes: "Paragraphs/Layout Builder, multiple view modes",
  },
  {
    techStack: "DRUPAL",
    category: "Content Architecture",
    taskType: "Content type (enterprise, 25+ fields, workflows)",
    lowHours: 20,
    highHours: 40,
    notes: "Editorial workflows, revisions, access control",
  },
  {
    techStack: "DRUPAL",
    category: "Content Architecture",
    taskType: "Taxonomy vocabulary + terms",
    lowHours: 2,
    highHours: 4,
    notes: "More if hierarchical with 100+ terms",
  },
  {
    techStack: "DRUPAL",
    category: "Content Architecture",
    taskType: "Views (simple listing)",
    lowHours: 2,
    highHours: 4,
    notes: "Basic content listing with filters",
  },
  {
    techStack: "DRUPAL",
    category: "Content Architecture",
    taskType: "Views (complex, exposed filters, AJAX)",
    lowHours: 8,
    highHours: 16,
    notes: "Faceted search, contextual filters, REST export",
  },
  {
    techStack: "DRUPAL",
    category: "Content Architecture",
    taskType: "Media types configuration",
    lowHours: 4,
    highHours: 8,
    notes: "Image, video, document, remote video",
  },

  // --- Drupal: Custom Module Development ---
  {
    techStack: "DRUPAL",
    category: "Custom Module Development",
    taskType: "Custom module (simple)",
    lowHours: 8,
    highHours: 24,
    notes: "Custom block plugin, simple form alter, token provider",
  },
  {
    techStack: "DRUPAL",
    category: "Custom Module Development",
    taskType: "Custom module (medium)",
    lowHours: 24,
    highHours: 60,
    notes: "Custom entity type, queue worker, event subscriber with business logic",
  },
  {
    techStack: "DRUPAL",
    category: "Custom Module Development",
    taskType: "Custom module (complex)",
    lowHours: 60,
    highHours: 160,
    notes: "Custom migration source plugin, complex access control, API integration service",
  },

  // --- Drupal: Contrib Module Configuration ---
  {
    techStack: "DRUPAL",
    category: "Contrib Module Configuration",
    taskType: "Paragraphs / Layout Builder",
    lowHours: 16,
    highHours: 40,
    notes: "Depends on number of component types",
  },
  {
    techStack: "DRUPAL",
    category: "Contrib Module Configuration",
    taskType: "Search API + Solr/Elasticsearch",
    lowHours: 40,
    highHours: 80,
    notes: "Including facets, autocomplete, custom processors",
  },
  {
    techStack: "DRUPAL",
    category: "Contrib Module Configuration",
    taskType: "Webform",
    lowHours: 8,
    highHours: 24,
    notes: "Per complex form with conditional logic",
  },
  {
    techStack: "DRUPAL",
    category: "Contrib Module Configuration",
    taskType: "Commerce",
    lowHours: 80,
    highHours: 200,
    notes: "Depends on product types, payment gateways, tax rules",
  },
  {
    techStack: "DRUPAL",
    category: "Contrib Module Configuration",
    taskType: "Group / Organic Groups",
    lowHours: 40,
    highHours: 80,
    notes: "Multi-group content access patterns",
  },
  {
    techStack: "DRUPAL",
    category: "Contrib Module Configuration",
    taskType: "JSON:API / GraphQL (decoupled)",
    lowHours: 24,
    highHours: 60,
    notes: "Schema customization, auth, includes/fields",
  },

  // --- Drupal: Theme Development ---
  {
    techStack: "DRUPAL",
    category: "Theme Development",
    taskType: "Admin theme customization",
    lowHours: 8,
    highHours: 16,
    notes: "Gin/Claro tweaks",
  },
  {
    techStack: "DRUPAL",
    category: "Theme Development",
    taskType: "Sub-theme (Starter kit, e.g., Olivero)",
    lowHours: 40,
    highHours: 80,
    notes: "Basic frontend implementation",
  },
  {
    techStack: "DRUPAL",
    category: "Theme Development",
    taskType: "Custom theme (component-based)",
    lowHours: 80,
    highHours: 200,
    notes: "Full Storybook/Pattern Lab integration",
  },
  {
    techStack: "DRUPAL",
    category: "Theme Development",
    taskType: "Design system implementation",
    lowHours: 120,
    highHours: 300,
    notes: "Shared component library across projects",
  },

  // --- Drupal: Migration ---
  {
    techStack: "DRUPAL",
    category: "Migration",
    taskType: "Content type migration base effort",
    lowHours: 16,
    highHours: 40,
    notes: "Source plugin + process + destination + QA per content type",
  },
  {
    techStack: "DRUPAL",
    category: "Migration",
    taskType: "Drupal 7 to Drupal 10/11",
    lowHours: 16,
    highHours: 40,
    notes: "1x baseline — core migration framework, well-supported path",
  },
  {
    techStack: "DRUPAL",
    category: "Migration",
    taskType: "WordPress to Drupal",
    lowHours: 21,
    highHours: 60,
    notes: "1.3-1.5x multiplier — custom migration plugins, URL mapping",
  },
  {
    techStack: "DRUPAL",
    category: "Migration",
    taskType: "Static HTML to Drupal",
    lowHours: 24,
    highHours: 80,
    notes: "1.5-2x multiplier — content parsing, no structured source",
  },
  {
    techStack: "DRUPAL",
    category: "Migration",
    taskType: "Custom CMS / Database to Drupal",
    lowHours: 24,
    highHours: 100,
    notes: "1.5-2.5x multiplier — custom source plugins, data mapping",
  },
  {
    techStack: "DRUPAL",
    category: "Migration",
    taskType: "Sitecore / AEM to Drupal",
    lowHours: 32,
    highHours: 120,
    notes: "2-3x multiplier — complex content models, workflow mapping",
  },

  // --- Drupal: Decoupled / Headless ---
  {
    techStack: "DRUPAL",
    category: "Decoupled / Headless",
    taskType: "API design + JSON:API config",
    lowHours: 24,
    highHours: 40,
    notes: "Resource configuration, includes, field aliasing",
  },
  {
    techStack: "DRUPAL",
    category: "Decoupled / Headless",
    taskType: "GraphQL schema + resolvers",
    lowHours: 40,
    highHours: 80,
    notes: "If using GraphQL instead of JSON:API",
  },
  {
    techStack: "DRUPAL",
    category: "Decoupled / Headless",
    taskType: "Preview mode (draft content)",
    lowHours: 16,
    highHours: 40,
    notes: "Depends on frontend framework",
  },
  {
    techStack: "DRUPAL",
    category: "Decoupled / Headless",
    taskType: "Authentication for API consumers",
    lowHours: 16,
    highHours: 40,
    notes: "OAuth2, JWT, Simple OAuth module",
  },

  // --- Drupal: DevOps ---
  {
    techStack: "DRUPAL",
    category: "DevOps",
    taskType: "Config management (CMI) setup",
    lowHours: 8,
    highHours: 16,
    notes: "Config split, environment overrides",
  },
  {
    techStack: "DRUPAL",
    category: "DevOps",
    taskType: "CI/CD pipeline",
    lowHours: 24,
    highHours: 60,
    notes: "Linting, tests, deploy scripts, environments",
  },
  {
    techStack: "DRUPAL",
    category: "DevOps",
    taskType: "Hosting setup (Acquia/Pantheon/Platform.sh)",
    lowHours: 16,
    highHours: 40,
    notes: "Platform-specific configuration",
  },
  {
    techStack: "DRUPAL",
    category: "DevOps",
    taskType: "Hosting setup (custom/AWS/GCP)",
    lowHours: 40,
    highHours: 80,
    notes: "Docker, orchestration, CDN, SSL",
  },
  {
    techStack: "DRUPAL",
    category: "DevOps",
    taskType: "Performance tuning",
    lowHours: 16,
    highHours: 40,
    notes: "Caching layers, CDN, database optimization",
  },
  {
    techStack: "DRUPAL",
    category: "DevOps",
    taskType: "Security hardening",
    lowHours: 8,
    highHours: 24,
    notes: "CSP headers, permissions audit, update policy",
  },

  // --- Drupal: Integration Tiers ---
  {
    techStack: "DRUPAL",
    category: "Integration Tiers",
    taskType: "T1 — Simple integration",
    lowHours: 8,
    highHours: 16,
    notes: "One-way REST push/pull, well-documented API, no auth complexity. Examples: Analytics embed, RSS feed, simple webhook, social media embed",
  },
  {
    techStack: "DRUPAL",
    category: "Integration Tiers",
    taskType: "T2 — Standard integration",
    lowHours: 16,
    highHours: 32,
    notes: "Auth required (OAuth/API key), field mapping, error handling, retry logic. Examples: CRM sync, payment gateway, email service, Google Maps",
  },
  {
    techStack: "DRUPAL",
    category: "Integration Tiers",
    taskType: "T3 — Complex integration",
    lowHours: 32,
    highHours: 60,
    notes: "Bidirectional sync, real-time/webhooks, poorly documented API, multi-step auth, data transformation. Examples: ERP, SSO (SAML/LDAP), real-time inventory sync",
  },

  // --- Drupal: Always-Include Tasks (Backend) ---
  {
    techStack: "DRUPAL",
    category: "Always-Include Tasks",
    taskType: "Discovery & Requirements Analysis",
    lowHours: 8,
    highHours: 16,
    notes: "Kickoff, TOR deep-dive, architecture decisions",
  },
  {
    techStack: "DRUPAL",
    category: "Always-Include Tasks",
    taskType: "Environment Setup (Lando/DDEV, CI/CD)",
    lowHours: 6,
    highHours: 12,
    notes: "Local dev environment + basic pipeline",
  },
  {
    techStack: "DRUPAL",
    category: "Always-Include Tasks",
    taskType: "Drupal Installation & Base Configuration",
    lowHours: 4,
    highHours: 8,
    notes: "Site install, admin config, base modules",
  },
  {
    techStack: "DRUPAL",
    category: "Always-Include Tasks",
    taskType: "Configuration Management Setup (CMI)",
    lowHours: 4,
    highHours: 6,
    notes: "Config split, environment overrides",
  },
  {
    techStack: "DRUPAL",
    category: "Always-Include Tasks",
    taskType: "Roles & Permissions",
    lowHours: 4,
    highHours: 8,
    notes: "Role definitions, content access patterns",
  },
  {
    techStack: "DRUPAL",
    category: "Always-Include Tasks",
    taskType: "Media Library Setup",
    lowHours: 3,
    highHours: 6,
    notes: "Image styles, media types, file management",
  },
  {
    techStack: "DRUPAL",
    category: "Always-Include Tasks",
    taskType: "Deployment Pipeline",
    lowHours: 4,
    highHours: 8,
    notes: "Deploy scripts, environment promotion",
  },

  // --- Frontend: Design System / Theme Foundation ---
  {
    techStack: "DRUPAL",
    category: "Frontend: Design System / Theme Foundation",
    taskType: "Theme setup (from scratch)",
    lowHours: 16,
    highHours: 40,
    notes: "Build tooling (Gulp/Webpack/Vite), base config, folder structure",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Design System / Theme Foundation",
    taskType: "Theme setup (existing design system)",
    lowHours: 8,
    highHours: 16,
    notes: "Integrating provided design system tokens/variables",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Design System / Theme Foundation",
    taskType: "Design system creation",
    lowHours: 40,
    highHours: 80,
    notes: "Tokens, typography scale, color system, spacing, grid, breakpoints",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Design System / Theme Foundation",
    taskType: "Design system integration (reuse existing)",
    lowHours: 16,
    highHours: 32,
    notes: "Mapping existing design system to project components",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Design System / Theme Foundation",
    taskType: "Generic elements / styleguide",
    lowHours: 4,
    highHours: 8,
    notes: "Headings H1-H6, paragraphs, lists, CTAs, links, colors, fonts",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Design System / Theme Foundation",
    taskType: "Grid settings & layout system",
    lowHours: 4,
    highHours: 8,
    notes: "Column grid, container widths, responsive breakpoints",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Design System / Theme Foundation",
    taskType: "Image styles & responsive images",
    lowHours: 8,
    highHours: 24,
    notes: "Art direction, focal point, image styles (12-15 typical)",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Design System / Theme Foundation",
    taskType: "Animation & transitions (base)",
    lowHours: 4,
    highHours: 8,
    notes: "Micro-interactions, hover states, page transitions",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Design System / Theme Foundation",
    taskType: "Browser testing & cross-browser fixes",
    lowHours: 8,
    highHours: 16,
    notes: "Chrome, Safari, Firefox, Edge (current - 1)",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Design System / Theme Foundation",
    taskType: "Accessibility (WCAG AA compliance)",
    lowHours: 8,
    highHours: 24,
    notes: "Keyboard nav, ARIA, color contrast, screen reader testing",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Design System / Theme Foundation",
    taskType: "RTL / LTR support",
    lowHours: 8,
    highHours: 16,
    notes: "Bidirectional text, mirrored layouts",
  },

  // --- Frontend: Global Components ---
  {
    techStack: "DRUPAL",
    category: "Frontend: Global Components",
    taskType: "Header (simple — logo, nav, CTA)",
    lowHours: 8,
    highHours: 16,
    notes: "Responsive, sticky/fixed behavior, mobile hamburger",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Global Components",
    taskType: "Header (complex — mega menu, search, multi-level)",
    lowHours: 16,
    highHours: 32,
    notes: "Dropdown panels, search overlay, multi-column menus",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Global Components",
    taskType: "Footer (standard)",
    lowHours: 4,
    highHours: 8,
    notes: "Logo, links, social icons, copyright",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Global Components",
    taskType: "Footer (complex — multi-column, newsletter, sitemap)",
    lowHours: 8,
    highHours: 16,
    notes: "Newsletter signup, multi-column link groups, legal links",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Global Components",
    taskType: "Navigation (primary)",
    lowHours: 8,
    highHours: 16,
    notes: "Multi-level dropdown, mobile drawer, active states",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Global Components",
    taskType: "Navigation (breadcrumb)",
    lowHours: 2,
    highHours: 4,
    notes: "Schema markup, responsive truncation",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Global Components",
    taskType: "Navigation (sidebar/secondary)",
    lowHours: 4,
    highHours: 8,
    notes: "Collapsible, active trail highlighting",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Global Components",
    taskType: "Search bar (basic)",
    lowHours: 4,
    highHours: 8,
    notes: "Input, submit, clear, mobile responsive",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Global Components",
    taskType: "Search bar (with autocomplete/suggestions)",
    lowHours: 8,
    highHours: 16,
    notes: "Dropdown suggestions, keyboard navigation, debounce",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Global Components",
    taskType: "Skip navigation / accessibility nav",
    lowHours: 2,
    highHours: 4,
    notes: "Skip links, focus management",
  },

  // --- Frontend: Content Components ---
  {
    techStack: "DRUPAL",
    category: "Frontend: Content Components",
    taskType: "Hero banner (simple — image, title, CTA)",
    lowHours: 4,
    highHours: 8,
    notes: "Responsive image, overlay text, single CTA",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Content Components",
    taskType: "Hero banner (complex — video, carousel, animated)",
    lowHours: 12,
    highHours: 24,
    notes: "Video background, slide transitions, multiple CTAs",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Content Components",
    taskType: "Card (basic — image, title, excerpt, link)",
    lowHours: 4,
    highHours: 8,
    notes: "Responsive, hover states, image aspect ratio",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Content Components",
    taskType: "Card (complex — tags, date, author, multiple CTAs)",
    lowHours: 8,
    highHours: 12,
    notes: "Metadata, badge overlays, multi-action",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Content Components",
    taskType: "Card grid / listing layout",
    lowHours: 4,
    highHours: 8,
    notes: "Responsive grid, load more / pagination",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Content Components",
    taskType: "Carousel / slider",
    lowHours: 8,
    highHours: 16,
    notes: "Touch/swipe, dots/arrows, autoplay, a11y",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Content Components",
    taskType: "Accordion / collapsible",
    lowHours: 4,
    highHours: 8,
    notes: "Expand/collapse, animation, multi-open vs single",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Content Components",
    taskType: "Tabs",
    lowHours: 4,
    highHours: 8,
    notes: "Responsive (tabs → accordion on mobile), keyboard nav",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Content Components",
    taskType: "Modal / dialog",
    lowHours: 4,
    highHours: 8,
    notes: "Focus trap, backdrop, close on escape, a11y",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Content Components",
    taskType: "Table (responsive)",
    lowHours: 4,
    highHours: 8,
    notes: "Horizontal scroll, stacked on mobile, sortable headers",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Content Components",
    taskType: "CTA banner / callout",
    lowHours: 4,
    highHours: 6,
    notes: "Background color/image, text, button(s)",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Content Components",
    taskType: "Testimonial / quote block",
    lowHours: 4,
    highHours: 6,
    notes: "Attribution, avatar, quote styling",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Content Components",
    taskType: "Statistics / counter block",
    lowHours: 4,
    highHours: 8,
    notes: "Animated counters, grid layout",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Content Components",
    taskType: "Timeline",
    lowHours: 8,
    highHours: 16,
    notes: "Vertical/horizontal, responsive, milestone markers",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Content Components",
    taskType: "Map embed (Google/Leaflet)",
    lowHours: 4,
    highHours: 8,
    notes: "Responsive iframe or interactive map",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Content Components",
    taskType: "Social media feed embed",
    lowHours: 4,
    highHours: 8,
    notes: "Twitter/Instagram/LinkedIn embed, responsive",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Content Components",
    taskType: "Video embed (YouTube/Vimeo)",
    lowHours: 4,
    highHours: 6,
    notes: "Responsive 16:9, lazy load, thumbnail fallback",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Content Components",
    taskType: "Image gallery / lightbox",
    lowHours: 8,
    highHours: 16,
    notes: "Grid layout, lightbox viewer, touch gestures",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Content Components",
    taskType: "FAQ section",
    lowHours: 4,
    highHours: 8,
    notes: "Accordion-based, schema markup",
  },

  // --- Frontend: Form Components ---
  {
    techStack: "DRUPAL",
    category: "Frontend: Form Components",
    taskType: "Contact form (basic)",
    lowHours: 4,
    highHours: 8,
    notes: "Name, email, message, validation, submit",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Form Components",
    taskType: "Multi-step form",
    lowHours: 12,
    highHours: 24,
    notes: "Step indicator, validation per step, summary",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Form Components",
    taskType: "Newsletter signup",
    lowHours: 2,
    highHours: 4,
    notes: "Email input, submit, success/error states",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Form Components",
    taskType: "Search filters / faceted search UI",
    lowHours: 8,
    highHours: 16,
    notes: "Checkboxes, range sliders, active filter tags, clear all",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Form Components",
    taskType: "File upload component",
    lowHours: 4,
    highHours: 8,
    notes: "Drag & drop, progress bar, file type validation",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Form Components",
    taskType: "Date picker",
    lowHours: 4,
    highHours: 8,
    notes: "Calendar widget, range selection, a11y",
  },

  // --- Frontend: Page Templates ---
  {
    techStack: "DRUPAL",
    category: "Frontend: Page Templates",
    taskType: "Homepage",
    lowHours: 16,
    highHours: 32,
    notes: "Assembly of multiple components, unique layout",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Page Templates",
    taskType: "Landing page (flexible/builder)",
    lowHours: 12,
    highHours: 24,
    notes: "Component-based assembly, layout variations",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Page Templates",
    taskType: "Article / blog detail",
    lowHours: 8,
    highHours: 16,
    notes: "Long-form content, sidebar, related articles",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Page Templates",
    taskType: "Listing page (archive/index)",
    lowHours: 8,
    highHours: 16,
    notes: "Filters, pagination, card grid",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Page Templates",
    taskType: "Detail page (generic)",
    lowHours: 8,
    highHours: 12,
    notes: "Content region, sidebar, metadata",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Page Templates",
    taskType: "Search results page",
    lowHours: 8,
    highHours: 16,
    notes: "Result cards, facets, pagination, empty state",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Page Templates",
    taskType: "Error pages (404, 500)",
    lowHours: 4,
    highHours: 6,
    notes: "Branded, helpful navigation",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Page Templates",
    taskType: "User dashboard / profile",
    lowHours: 12,
    highHours: 24,
    notes: "Tabs, data tables, action buttons",
  },

  // --- Frontend: Decoupled / Headless Frontend Overhead ---
  {
    techStack: "DRUPAL",
    category: "Frontend: Decoupled / Headless Overhead",
    taskType: "SSR/SSG setup (Next.js/Nuxt)",
    lowHours: 16,
    highHours: 32,
    notes: "Routing, data fetching, build config",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Decoupled / Headless Overhead",
    taskType: "API integration layer",
    lowHours: 16,
    highHours: 40,
    notes: "REST/GraphQL client, caching, error handling",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Decoupled / Headless Overhead",
    taskType: "Preview mode (draft content) — frontend",
    lowHours: 12,
    highHours: 24,
    notes: "Authenticated preview, draft rendering",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Decoupled / Headless Overhead",
    taskType: "Auth flow (frontend)",
    lowHours: 8,
    highHours: 16,
    notes: "Login/logout, token management, protected routes",
  },

  // =========================================================================
  // WORDPRESS BENCHMARKS
  // =========================================================================

  // --- WordPress: Content Architecture ---
  {
    techStack: "WORDPRESS",
    category: "Content Architecture",
    taskType: "Custom Post Type (simple, ACF/CPT UI)",
    lowHours: 4,
    highHours: 8,
    notes: "Registration, labels, admin columns, basic meta",
  },
  {
    techStack: "WORDPRESS",
    category: "Content Architecture",
    taskType: "Custom Post Type (complex, ACF Pro, relationships, conditional logic)",
    lowHours: 8,
    highHours: 16,
    notes: "Relationship fields, conditional logic, multiple field groups",
  },
  {
    techStack: "WORDPRESS",
    category: "Content Architecture",
    taskType: "Taxonomy setup (categories, tags, custom)",
    lowHours: 2,
    highHours: 4,
    notes: "More if hierarchical with 100+ terms or custom rewrite rules",
  },
  {
    techStack: "WORDPRESS",
    category: "Content Architecture",
    taskType: "Custom Fields (ACF field groups)",
    lowHours: 4,
    highHours: 8,
    notes: "Field group config, display templates, validation rules — per group",
  },
  {
    techStack: "WORDPRESS",
    category: "Content Architecture",
    taskType: "Advanced Custom Queries (WP_Query, custom REST endpoints)",
    lowHours: 8,
    highHours: 16,
    notes: "Complex query args, meta queries, custom REST routes",
  },
  {
    techStack: "WORDPRESS",
    category: "Content Architecture",
    taskType: "Page Builder configuration (Gutenberg blocks, patterns)",
    lowHours: 8,
    highHours: 16,
    notes: "Custom block registration, block patterns, template parts",
  },

  // --- WordPress: Plugin Development ---
  {
    techStack: "WORDPRESS",
    category: "Plugin Development",
    taskType: "Custom plugin (simple)",
    lowHours: 8,
    highHours: 16,
    notes: "Shortcode, widget, simple filter/action hook, custom admin notice",
  },
  {
    techStack: "WORDPRESS",
    category: "Plugin Development",
    taskType: "Custom plugin (medium)",
    lowHours: 16,
    highHours: 32,
    notes: "Admin settings page (Settings API), custom admin UI, AJAX handlers",
  },
  {
    techStack: "WORDPRESS",
    category: "Plugin Development",
    taskType: "Custom plugin (complex)",
    lowHours: 32,
    highHours: 60,
    notes: "Custom DB tables, REST API integration, background processing, licensing",
  },

  // --- WordPress: Plugin Configuration ---
  {
    techStack: "WORDPRESS",
    category: "Plugin Configuration",
    taskType: "WooCommerce basic setup",
    lowHours: 16,
    highHours: 24,
    notes: "Products, payments, shipping, tax, email templates",
  },
  {
    techStack: "WORDPRESS",
    category: "Plugin Configuration",
    taskType: "WooCommerce custom extensions",
    lowHours: 24,
    highHours: 48,
    notes: "Custom gateways, product types, checkout fields, subscription logic",
  },
  {
    techStack: "WORDPRESS",
    category: "Plugin Configuration",
    taskType: "ACF Pro advanced configuration",
    lowHours: 8,
    highHours: 16,
    notes: "Flexible content, gallery fields, options pages, Gutenberg integration",
  },
  {
    techStack: "WORDPRESS",
    category: "Plugin Configuration",
    taskType: "Yoast SEO / Rank Math configuration",
    lowHours: 4,
    highHours: 8,
    notes: "Schema setup, sitemap config, social previews, redirects",
  },
  {
    techStack: "WORDPRESS",
    category: "Plugin Configuration",
    taskType: "Gravity Forms / WPForms setup",
    lowHours: 4,
    highHours: 8,
    notes: "Per complex form with conditional logic, notifications, and confirmations",
  },
  {
    techStack: "WORDPRESS",
    category: "Plugin Configuration",
    taskType: "WPML / Polylang multilingual setup",
    lowHours: 16,
    highHours: 32,
    notes: "Language switcher, string translation, WooCommerce multilingual",
  },
  {
    techStack: "WORDPRESS",
    category: "Plugin Configuration",
    taskType: "WP Rocket / caching configuration",
    lowHours: 4,
    highHours: 8,
    notes: "Cache rules, CDN integration, file optimization, exclusions",
  },
  {
    techStack: "WORDPRESS",
    category: "Plugin Configuration",
    taskType: "Wordfence / security hardening",
    lowHours: 8,
    highHours: 12,
    notes: "Firewall rules, malware scan schedule, login security, alerts",
  },
  {
    techStack: "WORDPRESS",
    category: "Plugin Configuration",
    taskType: "SearchWP / Relevanssi custom search",
    lowHours: 8,
    highHours: 16,
    notes: "Index configuration, custom weights, faceted filtering, AJAX search",
  },

  // --- WordPress: Theme Development ---
  {
    techStack: "WORDPRESS",
    category: "Theme Development",
    taskType: "Child theme (existing parent)",
    lowHours: 8,
    highHours: 16,
    notes: "Style overrides, template overrides, additional hooks",
  },
  {
    techStack: "WORDPRESS",
    category: "Theme Development",
    taskType: "Custom theme (starter theme — Sage/Underscores)",
    lowHours: 24,
    highHours: 40,
    notes: "Full classic theme build from starter, no block/FSE overhead",
  },
  {
    techStack: "WORDPRESS",
    category: "Theme Development",
    taskType: "Block theme (Full Site Editing)",
    lowHours: 32,
    highHours: 48,
    notes: "theme.json, templates, template parts, block patterns, style variations",
  },
  {
    techStack: "WORDPRESS",
    category: "Theme Development",
    taskType: "Classic theme to block theme conversion",
    lowHours: 40,
    highHours: 60,
    notes: "Template re-implementation, global styles migration, block pattern library",
  },

  // --- WordPress: Migration ---
  {
    techStack: "WORDPRESS",
    category: "Migration",
    taskType: "WordPress version upgrade (major)",
    lowHours: 8,
    highHours: 16,
    notes: "Plugin compatibility audit, PHP version check, staging test cycle",
  },
  {
    techStack: "WORDPRESS",
    category: "Migration",
    taskType: "Drupal to WordPress",
    lowHours: 40,
    highHours: 80,
    notes: "Custom migration scripts, URL mapping, taxonomy mapping, media re-import",
  },
  {
    techStack: "WORDPRESS",
    category: "Migration",
    taskType: "Wix / Squarespace to WordPress",
    lowHours: 24,
    highHours: 40,
    notes: "Export-limited, manual content reconstruction likely required",
  },
  {
    techStack: "WORDPRESS",
    category: "Migration",
    taskType: "Static HTML to WordPress",
    lowHours: 16,
    highHours: 32,
    notes: "Content parsing, image harvesting, template mapping",
  },
  {
    techStack: "WORDPRESS",
    category: "Migration",
    taskType: "Legacy CMS to WordPress",
    lowHours: 40,
    highHours: 80,
    notes: "Custom source adapter, data mapping, URL redirect strategy",
  },
  {
    techStack: "WORDPRESS",
    category: "Migration",
    taskType: "Content migration (per 1000 posts)",
    lowHours: 8,
    highHours: 16,
    notes: "Includes post, meta, taxonomy terms, and featured image re-association",
  },

  // --- WordPress: DevOps ---
  {
    techStack: "WORDPRESS",
    category: "DevOps",
    taskType: "Environment setup (Local/Docker/Valet)",
    lowHours: 4,
    highHours: 8,
    notes: "Local dev tooling, DB import, wp-config wiring",
  },
  {
    techStack: "WORDPRESS",
    category: "DevOps",
    taskType: "wp-config environment management",
    lowHours: 4,
    highHours: 6,
    notes: "Constants per environment, .env integration (Bedrock/Trellis pattern)",
  },
  {
    techStack: "WORDPRESS",
    category: "DevOps",
    taskType: "CI/CD pipeline (GitHub Actions / Bitbucket)",
    lowHours: 8,
    highHours: 16,
    notes: "Lint, test, deploy-to-staging, deploy-to-prod with approvals",
  },
  {
    techStack: "WORDPRESS",
    category: "DevOps",
    taskType: "Hosting setup — managed (WP Engine / Kinsta)",
    lowHours: 4,
    highHours: 8,
    notes: "DNS, SSL, PHP version, cache configuration, backup schedule",
  },
  {
    techStack: "WORDPRESS",
    category: "DevOps",
    taskType: "Hosting setup — self-managed (VPS / cloud)",
    lowHours: 8,
    highHours: 16,
    notes: "Nginx/Apache, PHP-FPM, MySQL, SSL, swap, fail2ban, monitoring",
  },
  {
    techStack: "WORDPRESS",
    category: "DevOps",
    taskType: "Performance optimization (caching, CDN)",
    lowHours: 8,
    highHours: 16,
    notes: "Object cache (Redis), page cache, CDN rules, DB query optimization",
  },
  {
    techStack: "WORDPRESS",
    category: "DevOps",
    taskType: "Security hardening (headers, firewall, 2FA)",
    lowHours: 8,
    highHours: 12,
    notes: "CSP/HSTS headers, WAF rules, login protection, file permission audit",
  },
  {
    techStack: "WORDPRESS",
    category: "DevOps",
    taskType: "Backup & disaster recovery",
    lowHours: 4,
    highHours: 8,
    notes: "Automated off-site backup, restoration runbook, retention policy",
  },
  {
    techStack: "WORDPRESS",
    category: "DevOps",
    taskType: "Multisite setup",
    lowHours: 8,
    highHours: 16,
    notes: "Network activation, domain mapping, shared vs. per-site plugins",
  },

  // --- WordPress: Integration Tiers ---
  {
    techStack: "WORDPRESS",
    category: "Integration Tiers",
    taskType: "T1 — Simple integration",
    lowHours: 8,
    highHours: 16,
    notes: "One-way REST push/pull, well-documented API, no auth complexity. Examples: Analytics embed, RSS feed, simple webhook, social media embed, Google Maps iframe",
  },
  {
    techStack: "WORDPRESS",
    category: "Integration Tiers",
    taskType: "T2 — Standard integration",
    lowHours: 16,
    highHours: 32,
    notes: "Auth required (OAuth/API key), field mapping, error handling, retry logic. Examples: CRM sync (HubSpot, Salesforce basic), payment gateway, email service (Mailchimp/SendGrid), booking system",
  },
  {
    techStack: "WORDPRESS",
    category: "Integration Tiers",
    taskType: "T3 — Complex integration",
    lowHours: 32,
    highHours: 60,
    notes: "Bidirectional sync, real-time/webhooks, poorly documented API, multi-step auth, data transformation. Examples: ERP integration (SAP/NetSuite), SSO (SAML/LDAP), real-time inventory sync, custom middleware layer",
  },

  // --- WordPress: Always-Include Tasks ---
  {
    techStack: "WORDPRESS",
    category: "Always-Include Tasks",
    taskType: "Discovery & Requirements Analysis",
    lowHours: 16,
    highHours: 24,
    notes: "Kickoff, TOR deep-dive, plugin selection, architecture decisions",
  },
  {
    techStack: "WORDPRESS",
    category: "Always-Include Tasks",
    taskType: "Environment Setup (Local/Docker/Valet)",
    lowHours: 4,
    highHours: 8,
    notes: "Local dev environment + staging environment parity",
  },
  {
    techStack: "WORDPRESS",
    category: "Always-Include Tasks",
    taskType: "WordPress Installation & Base Configuration",
    lowHours: 4,
    highHours: 8,
    notes: "Site install, permalink structure, admin settings, timezone",
  },
  {
    techStack: "WORDPRESS",
    category: "Always-Include Tasks",
    taskType: "Plugin Management & Configuration",
    lowHours: 8,
    highHours: 16,
    notes: "Core plugin selection, license activation, baseline configuration",
  },
  {
    techStack: "WORDPRESS",
    category: "Always-Include Tasks",
    taskType: "Roles & Capabilities Setup",
    lowHours: 4,
    highHours: 8,
    notes: "Role definitions, custom capabilities, content access patterns",
  },
  {
    techStack: "WORDPRESS",
    category: "Always-Include Tasks",
    taskType: "Media Library Configuration",
    lowHours: 4,
    highHours: 8,
    notes: "Image sizes, upload limits, storage (local vs. S3/offload), EXIF stripping",
  },
  {
    techStack: "WORDPRESS",
    category: "Always-Include Tasks",
    taskType: "Deployment Pipeline",
    lowHours: 8,
    highHours: 16,
    notes: "Deploy scripts, WP-CLI sync commands, environment promotion workflow",
  },
  {
    techStack: "WORDPRESS",
    category: "Always-Include Tasks",
    taskType: "QA, Bug Fixes & Stabilisation",
    lowHours: 16,
    highHours: 24,
    notes: "End-of-sprint stabilisation, cross-browser/device testing, regression (approx 10-15% of total)",
  },

  // --- WordPress: Frontend: Design System / Theme Foundation ---
  {
    techStack: "WORDPRESS",
    category: "Frontend: Design System / Theme Foundation",
    taskType: "Theme setup (from scratch)",
    lowHours: 16,
    highHours: 40,
    notes: "Build tooling (Webpack/Vite/Gulp), base config, folder structure",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Design System / Theme Foundation",
    taskType: "Theme setup (existing design system)",
    lowHours: 8,
    highHours: 16,
    notes: "Integrating provided design system tokens/variables into theme",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Design System / Theme Foundation",
    taskType: "Design system creation",
    lowHours: 40,
    highHours: 80,
    notes: "Tokens, typography scale, color system, spacing, grid, breakpoints",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Design System / Theme Foundation",
    taskType: "Design system integration (reuse existing)",
    lowHours: 16,
    highHours: 32,
    notes: "Mapping existing design system to theme and block components",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Design System / Theme Foundation",
    taskType: "Design tokens / theme.json configuration",
    lowHours: 4,
    highHours: 8,
    notes: "Typography, colors, spacing, border-radius registered via theme.json",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Design System / Theme Foundation",
    taskType: "Typography system",
    lowHours: 4,
    highHours: 8,
    notes: "Headings H1-H6, body, captions, responsive fluid type scale",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Design System / Theme Foundation",
    taskType: "Color system",
    lowHours: 2,
    highHours: 4,
    notes: "Brand palette, semantic tokens, dark mode preparedness",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Design System / Theme Foundation",
    taskType: "Responsive grid & layout system",
    lowHours: 4,
    highHours: 8,
    notes: "Column grid, container widths, responsive breakpoints",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Design System / Theme Foundation",
    taskType: "Image sizes & responsive images",
    lowHours: 4,
    highHours: 8,
    notes: "add_image_size() definitions, srcset, art direction, focal point plugin",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Design System / Theme Foundation",
    taskType: "Accessibility (WCAG AA compliance)",
    lowHours: 8,
    highHours: 24,
    notes: "Keyboard nav, ARIA, color contrast, screen reader testing",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Design System / Theme Foundation",
    taskType: "RTL / LTR support",
    lowHours: 8,
    highHours: 16,
    notes: "Bidirectional text, rtl.css or logical properties",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Design System / Theme Foundation",
    taskType: "Dark mode support",
    lowHours: 8,
    highHours: 16,
    notes: "prefers-color-scheme + manual toggle, CSS custom property swap",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Design System / Theme Foundation",
    taskType: "Browser testing & cross-browser fixes",
    lowHours: 8,
    highHours: 16,
    notes: "Chrome, Safari, Firefox, Edge (current - 1)",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Design System / Theme Foundation",
    taskType: "Animation & transitions (base)",
    lowHours: 4,
    highHours: 8,
    notes: "Micro-interactions, hover states, scroll-triggered reveals",
  },

  // --- WordPress: Frontend: Global Components ---
  {
    techStack: "WORDPRESS",
    category: "Frontend: Global Components",
    taskType: "Header (simple — logo, nav, CTA)",
    lowHours: 8,
    highHours: 16,
    notes: "Responsive, sticky/fixed behavior, mobile hamburger",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Global Components",
    taskType: "Header (complex — mega menu, search, multi-level)",
    lowHours: 16,
    highHours: 32,
    notes: "Dropdown panels, search overlay, multi-column menus",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Global Components",
    taskType: "Footer (standard)",
    lowHours: 4,
    highHours: 8,
    notes: "Logo, links, social icons, copyright",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Global Components",
    taskType: "Footer (complex — multi-column, newsletter, sitemap)",
    lowHours: 8,
    highHours: 16,
    notes: "Newsletter signup, multi-column link groups, legal links",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Global Components",
    taskType: "Navigation (primary — wp_nav_menu)",
    lowHours: 8,
    highHours: 16,
    notes: "Multi-level dropdown, mobile drawer, active states, Walker class if needed",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Global Components",
    taskType: "Navigation (breadcrumb)",
    lowHours: 2,
    highHours: 4,
    notes: "Schema markup, responsive truncation, Yoast/Rank Math breadcrumb integration",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Global Components",
    taskType: "Navigation (sidebar/secondary)",
    lowHours: 4,
    highHours: 8,
    notes: "Collapsible, active page highlighting, widget-area backed",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Global Components",
    taskType: "Search bar (basic)",
    lowHours: 4,
    highHours: 8,
    notes: "get_search_form(), input, submit, clear, mobile responsive",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Global Components",
    taskType: "Search bar (with autocomplete/suggestions)",
    lowHours: 8,
    highHours: 16,
    notes: "AJAX-powered suggestions, keyboard navigation, debounce — SearchWP/custom",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Global Components",
    taskType: "Skip navigation / accessibility nav",
    lowHours: 2,
    highHours: 4,
    notes: "Skip links, focus management",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Global Components",
    taskType: "Back-to-top button",
    lowHours: 2,
    highHours: 4,
    notes: "Scroll threshold, smooth scroll, a11y button",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Global Components",
    taskType: "Cookie consent / GDPR banner",
    lowHours: 4,
    highHours: 8,
    notes: "Accept/reject, preference storage, analytics blocking until consent",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Global Components",
    taskType: "Notification / announcement bar",
    lowHours: 2,
    highHours: 4,
    notes: "Dismissible, cookie-persisted dismiss, CMS-editable via ACF options",
  },

  // --- WordPress: Frontend: Content Components ---
  {
    techStack: "WORDPRESS",
    category: "Frontend: Content Components",
    taskType: "Hero banner (simple — image, title, CTA)",
    lowHours: 4,
    highHours: 8,
    notes: "Responsive image, overlay text, single CTA",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Content Components",
    taskType: "Hero banner (complex — video, carousel, animated)",
    lowHours: 12,
    highHours: 24,
    notes: "Video background, slide transitions, multiple CTAs",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Content Components",
    taskType: "Card (basic — image, title, excerpt, link)",
    lowHours: 4,
    highHours: 8,
    notes: "Responsive, hover states, image aspect ratio",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Content Components",
    taskType: "Card (complex — tags, date, author, multiple CTAs)",
    lowHours: 8,
    highHours: 12,
    notes: "Metadata, badge overlays, multi-action",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Content Components",
    taskType: "Card grid / listing layout",
    lowHours: 4,
    highHours: 8,
    notes: "Responsive grid, load more / pagination via WP_Query",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Content Components",
    taskType: "Carousel / slider",
    lowHours: 8,
    highHours: 16,
    notes: "Touch/swipe, dots/arrows, autoplay, a11y — Swiper.js or equivalent",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Content Components",
    taskType: "Accordion / collapsible",
    lowHours: 4,
    highHours: 8,
    notes: "Expand/collapse, animation, multi-open vs single, schema markup for FAQ",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Content Components",
    taskType: "Tabs",
    lowHours: 4,
    highHours: 8,
    notes: "Responsive (tabs → accordion on mobile), keyboard nav, ARIA",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Content Components",
    taskType: "Modal / dialog",
    lowHours: 4,
    highHours: 8,
    notes: "Focus trap, backdrop, close on escape, a11y",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Content Components",
    taskType: "Table (responsive)",
    lowHours: 4,
    highHours: 8,
    notes: "Horizontal scroll, stacked on mobile, sortable headers",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Content Components",
    taskType: "Timeline",
    lowHours: 8,
    highHours: 16,
    notes: "Vertical/horizontal, responsive, milestone markers, ACF-backed",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Content Components",
    taskType: "Testimonial / quote block",
    lowHours: 4,
    highHours: 6,
    notes: "Attribution, avatar, quote styling, CPT or ACF repeater backed",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Content Components",
    taskType: "CTA banner / callout",
    lowHours: 4,
    highHours: 6,
    notes: "Background color/image, text, button(s), ACF options backed",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Content Components",
    taskType: "Image gallery / lightbox",
    lowHours: 8,
    highHours: 16,
    notes: "Grid layout, lightbox viewer, touch gestures, WP gallery or ACF gallery field",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Content Components",
    taskType: "Video embed (YouTube/Vimeo)",
    lowHours: 4,
    highHours: 6,
    notes: "Responsive 16:9, lazy load, thumbnail fallback, oEmbed or ACF",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Content Components",
    taskType: "Statistics / counter block",
    lowHours: 4,
    highHours: 8,
    notes: "Animated counters on scroll, grid layout, ACF repeater",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Content Components",
    taskType: "Pricing table / comparison",
    lowHours: 8,
    highHours: 16,
    notes: "Column comparison, feature matrix, toggle monthly/annual, ACF flexible",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Content Components",
    taskType: "Team members grid",
    lowHours: 4,
    highHours: 8,
    notes: "CPT-backed, photo, bio, social links, filtering by department",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Content Components",
    taskType: "FAQ section",
    lowHours: 4,
    highHours: 8,
    notes: "Accordion-based, FAQ schema markup, CPT or ACF repeater",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Content Components",
    taskType: "Social media feed embed",
    lowHours: 4,
    highHours: 8,
    notes: "Twitter/Instagram/LinkedIn embed, responsive, plugin or API-based",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Content Components",
    taskType: "Map embed (Google/Leaflet)",
    lowHours: 4,
    highHours: 8,
    notes: "Responsive iframe or interactive map with ACF-managed markers",
  },

  // --- WordPress: Frontend: Form Components ---
  {
    techStack: "WORDPRESS",
    category: "Frontend: Form Components",
    taskType: "Contact form (basic)",
    lowHours: 4,
    highHours: 8,
    notes: "Name, email, message, validation, submit — Gravity Forms / CF7 / WPForms",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Form Components",
    taskType: "Multi-step form",
    lowHours: 12,
    highHours: 24,
    notes: "Step indicator, validation per step, summary — Gravity Forms multi-page",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Form Components",
    taskType: "Newsletter signup",
    lowHours: 2,
    highHours: 4,
    notes: "Email input, submit, success/error states, Mailchimp/ConvertKit integration",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Form Components",
    taskType: "Search filters / faceted search UI",
    lowHours: 8,
    highHours: 16,
    notes: "Checkboxes, range sliders, active filter tags, clear all — SearchWP / FacetWP",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Form Components",
    taskType: "File upload component",
    lowHours: 4,
    highHours: 8,
    notes: "Drag & drop, progress bar, file type validation — Gravity Forms or custom",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Form Components",
    taskType: "Date picker",
    lowHours: 4,
    highHours: 8,
    notes: "Calendar widget, range selection, a11y — Flatpickr or Gravity Forms datepicker",
  },

  // --- WordPress: Frontend: Page Templates ---
  {
    techStack: "WORDPRESS",
    category: "Frontend: Page Templates",
    taskType: "Homepage",
    lowHours: 16,
    highHours: 32,
    notes: "Assembly of multiple components, unique layout, front-page.php or FSE template",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Page Templates",
    taskType: "Landing page (flexible/builder)",
    lowHours: 12,
    highHours: 24,
    notes: "ACF flexible content or Gutenberg block assembly, layout variations",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Page Templates",
    taskType: "Blog / post listing",
    lowHours: 8,
    highHours: 16,
    notes: "Category filter, pagination, card grid — index.php / archive.php",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Page Templates",
    taskType: "Article / post detail",
    lowHours: 8,
    highHours: 16,
    notes: "Long-form content, sidebar, related posts, author box — single.php",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Page Templates",
    taskType: "Search results page",
    lowHours: 8,
    highHours: 16,
    notes: "Result cards, facets, pagination, empty state — search.php",
  },
  {
    techStack: "WORDPRESS",
    category: "Frontend: Page Templates",
    taskType: "Error pages (404)",
    lowHours: 4,
    highHours: 6,
    notes: "Branded, helpful navigation suggestions — 404.php",
  },

  // =========================================================================
  // WORDPRESS + NEXT.JS (HEADLESS) BENCHMARKS
  // =========================================================================

  // --- WordPress + Next.js: Headless / Decoupled (Backend) ---
  {
    techStack: "WORDPRESS_NEXTJS",
    category: "Headless / Decoupled",
    taskType: "WPGraphQL setup + schema customization",
    lowHours: 16,
    highHours: 24,
    notes: "Plugin install, CPT/ACF exposure, query depth config, persisted queries",
  },
  {
    techStack: "WORDPRESS_NEXTJS",
    category: "Headless / Decoupled",
    taskType: "REST API custom endpoints",
    lowHours: 8,
    highHours: 16,
    notes: "Auth, schema validation, pagination, caching headers — per endpoint group",
  },
  {
    techStack: "WORDPRESS_NEXTJS",
    category: "Headless / Decoupled",
    taskType: "Preview mode (Faust.js / custom)",
    lowHours: 12,
    highHours: 20,
    notes: "Draft preview tokens, secret routes, on-demand revalidation",
  },
  {
    techStack: "WORDPRESS_NEXTJS",
    category: "Headless / Decoupled",
    taskType: "Authentication (JWT / NextAuth)",
    lowHours: 16,
    highHours: 24,
    notes: "WP JWT plugin, NextAuth provider, session handling, protected routes",
  },
  {
    techStack: "WORDPRESS_NEXTJS",
    category: "Headless / Decoupled",
    taskType: "ISR / SSG configuration",
    lowHours: 8,
    highHours: 12,
    notes: "revalidate strategy per content type, fallback handling",
  },
  {
    techStack: "WORDPRESS_NEXTJS",
    category: "Headless / Decoupled",
    taskType: "Image optimization (next/image + WP media)",
    lowHours: 4,
    highHours: 8,
    notes: "Domain allow-list, loader config, srcset mapping from WP",
  },

  // --- WordPress + Next.js: Frontend: Headless Overhead ---
  {
    techStack: "WORDPRESS_NEXTJS",
    category: "Frontend: Headless Overhead",
    taskType: "Next.js frontend scaffold (App Router)",
    lowHours: 16,
    highHours: 24,
    notes: "Project setup, routing, WP data fetching layer, env config",
  },
  {
    techStack: "WORDPRESS_NEXTJS",
    category: "Frontend: Headless Overhead",
    taskType: "API integration layer (WPGraphQL / REST client)",
    lowHours: 16,
    highHours: 40,
    notes: "GraphQL/REST client setup, caching, error handling, type generation",
  },
  {
    techStack: "WORDPRESS_NEXTJS",
    category: "Frontend: Headless Overhead",
    taskType: "SSR / SSG setup (Next.js)",
    lowHours: 16,
    highHours: 32,
    notes: "Routing, data fetching patterns, build config, revalidation",
  },
  {
    techStack: "WORDPRESS_NEXTJS",
    category: "Frontend: Headless Overhead",
    taskType: "Preview mode — frontend (draft content rendering)",
    lowHours: 12,
    highHours: 24,
    notes: "Authenticated preview routes, draft rendering, on-demand ISR trigger",
  },
  {
    techStack: "WORDPRESS_NEXTJS",
    category: "Frontend: Headless Overhead",
    taskType: "Auth flow — frontend (NextAuth / JWT)",
    lowHours: 8,
    highHours: 16,
    notes: "Login/logout, token management, protected routes, session persistence",
  },
  {
    techStack: "WORDPRESS_NEXTJS",
    category: "Frontend: Headless Overhead",
    taskType: "SEO meta (next-seo / app router metadata)",
    lowHours: 4,
    highHours: 8,
    notes: "Dynamic OG tags, canonical, robots, sitemap.xml generation from WP data",
  },
  {
    techStack: "WORDPRESS_NEXTJS",
    category: "Frontend: Headless Overhead",
    taskType: "Image optimization — next/image integration",
    lowHours: 4,
    highHours: 8,
    notes: "WP media domain config, srcset mapping, blur placeholder, lazy loading",
  },
];

async function main() {
  console.log(`Seeding ${benchmarks.length} benchmark entries...`);

  for (const benchmark of benchmarks) {
    await prisma.benchmark.upsert({
      where: {
        // Use a composite unique key based on techStack + category + taskType
        // Since schema has no unique constraint on these, we find-or-create via create+update
        // Prisma upsert requires a unique where — use a generated stable id approach via findFirst
        id: (
          await prisma.benchmark.findFirst({
            where: {
              techStack: benchmark.techStack,
              category: benchmark.category,
              taskType: benchmark.taskType,
            },
            select: { id: true },
          })
        )?.id ?? "non-existent-id",
      },
      update: {
        lowHours: benchmark.lowHours,
        highHours: benchmark.highHours,
        notes: benchmark.notes,
      },
      create: {
        techStack: benchmark.techStack,
        category: benchmark.category,
        taskType: benchmark.taskType,
        lowHours: benchmark.lowHours,
        highHours: benchmark.highHours,
        notes: benchmark.notes,
      },
    });
  }

  console.log("Benchmark seeding complete.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
