import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../src/generated/prisma/client";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter });

type BenchmarkSeed = {
  techStack: "DRUPAL";
  category: string;
  taskType: string;
  lowHours: number;
  highHours: number;
  notes?: string;
};

const benchmarks: BenchmarkSeed[] = [
  // --- Drupal: Content Architecture ---
  {
    techStack: "DRUPAL",
    category: "Content Architecture",
    taskType: "Content type (simple, < 10 fields)",
    lowHours: 4,
    highHours: 8,
    notes: "Including form display, view modes",
  },
  {
    techStack: "DRUPAL",
    category: "Content Architecture",
    taskType: "Content type (complex, 10-25 fields)",
    lowHours: 8,
    highHours: 20,
    notes: "Paragraphs/Layout Builder, multiple view modes",
  },
  {
    techStack: "DRUPAL",
    category: "Content Architecture",
    taskType: "Content type (enterprise, 25+ fields, workflows)",
    lowHours: 20,
    highHours: 40,
    notes: "Editorial workflows, revisions, access control",
  },
  {
    techStack: "DRUPAL",
    category: "Content Architecture",
    taskType: "Taxonomy vocabulary + terms",
    lowHours: 2,
    highHours: 4,
    notes: "More if hierarchical with 100+ terms",
  },
  {
    techStack: "DRUPAL",
    category: "Content Architecture",
    taskType: "Views (simple listing)",
    lowHours: 2,
    highHours: 4,
    notes: "Basic content listing with filters",
  },
  {
    techStack: "DRUPAL",
    category: "Content Architecture",
    taskType: "Views (complex, exposed filters, AJAX)",
    lowHours: 8,
    highHours: 16,
    notes: "Faceted search, contextual filters, REST export",
  },
  {
    techStack: "DRUPAL",
    category: "Content Architecture",
    taskType: "Media types configuration",
    lowHours: 4,
    highHours: 8,
    notes: "Image, video, document, remote video",
  },

  // --- Drupal: Custom Module Development ---
  {
    techStack: "DRUPAL",
    category: "Custom Module Development",
    taskType: "Custom module (simple)",
    lowHours: 8,
    highHours: 24,
    notes: "Custom block plugin, simple form alter, token provider",
  },
  {
    techStack: "DRUPAL",
    category: "Custom Module Development",
    taskType: "Custom module (medium)",
    lowHours: 24,
    highHours: 60,
    notes: "Custom entity type, queue worker, event subscriber with business logic",
  },
  {
    techStack: "DRUPAL",
    category: "Custom Module Development",
    taskType: "Custom module (complex)",
    lowHours: 60,
    highHours: 160,
    notes: "Custom migration source plugin, complex access control, API integration service",
  },

  // --- Drupal: Contrib Module Configuration ---
  {
    techStack: "DRUPAL",
    category: "Contrib Module Configuration",
    taskType: "Paragraphs / Layout Builder",
    lowHours: 16,
    highHours: 40,
    notes: "Depends on number of component types",
  },
  {
    techStack: "DRUPAL",
    category: "Contrib Module Configuration",
    taskType: "Search API + Solr/Elasticsearch",
    lowHours: 40,
    highHours: 80,
    notes: "Including facets, autocomplete, custom processors",
  },
  {
    techStack: "DRUPAL",
    category: "Contrib Module Configuration",
    taskType: "Webform",
    lowHours: 8,
    highHours: 24,
    notes: "Per complex form with conditional logic",
  },
  {
    techStack: "DRUPAL",
    category: "Contrib Module Configuration",
    taskType: "Commerce",
    lowHours: 80,
    highHours: 200,
    notes: "Depends on product types, payment gateways, tax rules",
  },
  {
    techStack: "DRUPAL",
    category: "Contrib Module Configuration",
    taskType: "Group / Organic Groups",
    lowHours: 40,
    highHours: 80,
    notes: "Multi-group content access patterns",
  },
  {
    techStack: "DRUPAL",
    category: "Contrib Module Configuration",
    taskType: "JSON:API / GraphQL (decoupled)",
    lowHours: 24,
    highHours: 60,
    notes: "Schema customization, auth, includes/fields",
  },

  // --- Drupal: Theme Development ---
  {
    techStack: "DRUPAL",
    category: "Theme Development",
    taskType: "Admin theme customization",
    lowHours: 8,
    highHours: 16,
    notes: "Gin/Claro tweaks",
  },
  {
    techStack: "DRUPAL",
    category: "Theme Development",
    taskType: "Sub-theme (Starter kit, e.g., Olivero)",
    lowHours: 40,
    highHours: 80,
    notes: "Basic frontend implementation",
  },
  {
    techStack: "DRUPAL",
    category: "Theme Development",
    taskType: "Custom theme (component-based)",
    lowHours: 80,
    highHours: 200,
    notes: "Full Storybook/Pattern Lab integration",
  },
  {
    techStack: "DRUPAL",
    category: "Theme Development",
    taskType: "Design system implementation",
    lowHours: 120,
    highHours: 300,
    notes: "Shared component library across projects",
  },

  // --- Drupal: Migration ---
  {
    techStack: "DRUPAL",
    category: "Migration",
    taskType: "Content type migration base effort",
    lowHours: 16,
    highHours: 40,
    notes: "Source plugin + process + destination + QA per content type",
  },
  {
    techStack: "DRUPAL",
    category: "Migration",
    taskType: "Drupal 7 to Drupal 10/11",
    lowHours: 16,
    highHours: 40,
    notes: "1x baseline — core migration framework, well-supported path",
  },
  {
    techStack: "DRUPAL",
    category: "Migration",
    taskType: "WordPress to Drupal",
    lowHours: 21,
    highHours: 60,
    notes: "1.3-1.5x multiplier — custom migration plugins, URL mapping",
  },
  {
    techStack: "DRUPAL",
    category: "Migration",
    taskType: "Static HTML to Drupal",
    lowHours: 24,
    highHours: 80,
    notes: "1.5-2x multiplier — content parsing, no structured source",
  },
  {
    techStack: "DRUPAL",
    category: "Migration",
    taskType: "Custom CMS / Database to Drupal",
    lowHours: 24,
    highHours: 100,
    notes: "1.5-2.5x multiplier — custom source plugins, data mapping",
  },
  {
    techStack: "DRUPAL",
    category: "Migration",
    taskType: "Sitecore / AEM to Drupal",
    lowHours: 32,
    highHours: 120,
    notes: "2-3x multiplier — complex content models, workflow mapping",
  },

  // --- Drupal: Decoupled / Headless ---
  {
    techStack: "DRUPAL",
    category: "Decoupled / Headless",
    taskType: "API design + JSON:API config",
    lowHours: 24,
    highHours: 40,
    notes: "Resource configuration, includes, field aliasing",
  },
  {
    techStack: "DRUPAL",
    category: "Decoupled / Headless",
    taskType: "GraphQL schema + resolvers",
    lowHours: 40,
    highHours: 80,
    notes: "If using GraphQL instead of JSON:API",
  },
  {
    techStack: "DRUPAL",
    category: "Decoupled / Headless",
    taskType: "Preview mode (draft content)",
    lowHours: 16,
    highHours: 40,
    notes: "Depends on frontend framework",
  },
  {
    techStack: "DRUPAL",
    category: "Decoupled / Headless",
    taskType: "Authentication for API consumers",
    lowHours: 16,
    highHours: 40,
    notes: "OAuth2, JWT, Simple OAuth module",
  },

  // --- Drupal: DevOps ---
  {
    techStack: "DRUPAL",
    category: "DevOps",
    taskType: "Config management (CMI) setup",
    lowHours: 8,
    highHours: 16,
    notes: "Config split, environment overrides",
  },
  {
    techStack: "DRUPAL",
    category: "DevOps",
    taskType: "CI/CD pipeline",
    lowHours: 24,
    highHours: 60,
    notes: "Linting, tests, deploy scripts, environments",
  },
  {
    techStack: "DRUPAL",
    category: "DevOps",
    taskType: "Hosting setup (Acquia/Pantheon/Platform.sh)",
    lowHours: 16,
    highHours: 40,
    notes: "Platform-specific configuration",
  },
  {
    techStack: "DRUPAL",
    category: "DevOps",
    taskType: "Hosting setup (custom/AWS/GCP)",
    lowHours: 40,
    highHours: 80,
    notes: "Docker, orchestration, CDN, SSL",
  },
  {
    techStack: "DRUPAL",
    category: "DevOps",
    taskType: "Performance tuning",
    lowHours: 16,
    highHours: 40,
    notes: "Caching layers, CDN, database optimization",
  },
  {
    techStack: "DRUPAL",
    category: "DevOps",
    taskType: "Security hardening",
    lowHours: 8,
    highHours: 24,
    notes: "CSP headers, permissions audit, update policy",
  },

  // --- Drupal: Integration Tiers ---
  {
    techStack: "DRUPAL",
    category: "Integration Tiers",
    taskType: "T1 — Simple integration",
    lowHours: 8,
    highHours: 16,
    notes: "One-way REST push/pull, well-documented API, no auth complexity. Examples: Analytics embed, RSS feed, simple webhook, social media embed",
  },
  {
    techStack: "DRUPAL",
    category: "Integration Tiers",
    taskType: "T2 — Standard integration",
    lowHours: 16,
    highHours: 32,
    notes: "Auth required (OAuth/API key), field mapping, error handling, retry logic. Examples: CRM sync, payment gateway, email service, Google Maps",
  },
  {
    techStack: "DRUPAL",
    category: "Integration Tiers",
    taskType: "T3 — Complex integration",
    lowHours: 32,
    highHours: 60,
    notes: "Bidirectional sync, real-time/webhooks, poorly documented API, multi-step auth, data transformation. Examples: ERP, SSO (SAML/LDAP), real-time inventory sync",
  },

  // --- Drupal: Always-Include Tasks (Backend) ---
  {
    techStack: "DRUPAL",
    category: "Always-Include Tasks",
    taskType: "Discovery & Requirements Analysis",
    lowHours: 8,
    highHours: 16,
    notes: "Kickoff, TOR deep-dive, architecture decisions",
  },
  {
    techStack: "DRUPAL",
    category: "Always-Include Tasks",
    taskType: "Environment Setup (Lando/DDEV, CI/CD)",
    lowHours: 6,
    highHours: 12,
    notes: "Local dev environment + basic pipeline",
  },
  {
    techStack: "DRUPAL",
    category: "Always-Include Tasks",
    taskType: "Drupal Installation & Base Configuration",
    lowHours: 4,
    highHours: 8,
    notes: "Site install, admin config, base modules",
  },
  {
    techStack: "DRUPAL",
    category: "Always-Include Tasks",
    taskType: "Configuration Management Setup (CMI)",
    lowHours: 4,
    highHours: 6,
    notes: "Config split, environment overrides",
  },
  {
    techStack: "DRUPAL",
    category: "Always-Include Tasks",
    taskType: "Roles & Permissions",
    lowHours: 4,
    highHours: 8,
    notes: "Role definitions, content access patterns",
  },
  {
    techStack: "DRUPAL",
    category: "Always-Include Tasks",
    taskType: "Media Library Setup",
    lowHours: 3,
    highHours: 6,
    notes: "Image styles, media types, file management",
  },
  {
    techStack: "DRUPAL",
    category: "Always-Include Tasks",
    taskType: "Deployment Pipeline",
    lowHours: 4,
    highHours: 8,
    notes: "Deploy scripts, environment promotion",
  },

  // --- Frontend: Design System / Theme Foundation ---
  {
    techStack: "DRUPAL",
    category: "Frontend: Design System / Theme Foundation",
    taskType: "Theme setup (from scratch)",
    lowHours: 16,
    highHours: 40,
    notes: "Build tooling (Gulp/Webpack/Vite), base config, folder structure",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Design System / Theme Foundation",
    taskType: "Theme setup (existing design system)",
    lowHours: 8,
    highHours: 16,
    notes: "Integrating provided design system tokens/variables",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Design System / Theme Foundation",
    taskType: "Design system creation",
    lowHours: 40,
    highHours: 80,
    notes: "Tokens, typography scale, color system, spacing, grid, breakpoints",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Design System / Theme Foundation",
    taskType: "Design system integration (reuse existing)",
    lowHours: 16,
    highHours: 32,
    notes: "Mapping existing design system to project components",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Design System / Theme Foundation",
    taskType: "Generic elements / styleguide",
    lowHours: 4,
    highHours: 8,
    notes: "Headings H1-H6, paragraphs, lists, CTAs, links, colors, fonts",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Design System / Theme Foundation",
    taskType: "Grid settings & layout system",
    lowHours: 4,
    highHours: 8,
    notes: "Column grid, container widths, responsive breakpoints",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Design System / Theme Foundation",
    taskType: "Image styles & responsive images",
    lowHours: 8,
    highHours: 24,
    notes: "Art direction, focal point, image styles (12-15 typical)",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Design System / Theme Foundation",
    taskType: "Animation & transitions (base)",
    lowHours: 4,
    highHours: 8,
    notes: "Micro-interactions, hover states, page transitions",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Design System / Theme Foundation",
    taskType: "Browser testing & cross-browser fixes",
    lowHours: 8,
    highHours: 16,
    notes: "Chrome, Safari, Firefox, Edge (current - 1)",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Design System / Theme Foundation",
    taskType: "Accessibility (WCAG AA compliance)",
    lowHours: 8,
    highHours: 24,
    notes: "Keyboard nav, ARIA, color contrast, screen reader testing",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Design System / Theme Foundation",
    taskType: "RTL / LTR support",
    lowHours: 8,
    highHours: 16,
    notes: "Bidirectional text, mirrored layouts",
  },

  // --- Frontend: Global Components ---
  {
    techStack: "DRUPAL",
    category: "Frontend: Global Components",
    taskType: "Header (simple — logo, nav, CTA)",
    lowHours: 8,
    highHours: 16,
    notes: "Responsive, sticky/fixed behavior, mobile hamburger",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Global Components",
    taskType: "Header (complex — mega menu, search, multi-level)",
    lowHours: 16,
    highHours: 32,
    notes: "Dropdown panels, search overlay, multi-column menus",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Global Components",
    taskType: "Footer (standard)",
    lowHours: 4,
    highHours: 8,
    notes: "Logo, links, social icons, copyright",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Global Components",
    taskType: "Footer (complex — multi-column, newsletter, sitemap)",
    lowHours: 8,
    highHours: 16,
    notes: "Newsletter signup, multi-column link groups, legal links",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Global Components",
    taskType: "Navigation (primary)",
    lowHours: 8,
    highHours: 16,
    notes: "Multi-level dropdown, mobile drawer, active states",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Global Components",
    taskType: "Navigation (breadcrumb)",
    lowHours: 2,
    highHours: 4,
    notes: "Schema markup, responsive truncation",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Global Components",
    taskType: "Navigation (sidebar/secondary)",
    lowHours: 4,
    highHours: 8,
    notes: "Collapsible, active trail highlighting",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Global Components",
    taskType: "Search bar (basic)",
    lowHours: 4,
    highHours: 8,
    notes: "Input, submit, clear, mobile responsive",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Global Components",
    taskType: "Search bar (with autocomplete/suggestions)",
    lowHours: 8,
    highHours: 16,
    notes: "Dropdown suggestions, keyboard navigation, debounce",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Global Components",
    taskType: "Skip navigation / accessibility nav",
    lowHours: 2,
    highHours: 4,
    notes: "Skip links, focus management",
  },

  // --- Frontend: Content Components ---
  {
    techStack: "DRUPAL",
    category: "Frontend: Content Components",
    taskType: "Hero banner (simple — image, title, CTA)",
    lowHours: 4,
    highHours: 8,
    notes: "Responsive image, overlay text, single CTA",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Content Components",
    taskType: "Hero banner (complex — video, carousel, animated)",
    lowHours: 12,
    highHours: 24,
    notes: "Video background, slide transitions, multiple CTAs",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Content Components",
    taskType: "Card (basic — image, title, excerpt, link)",
    lowHours: 4,
    highHours: 8,
    notes: "Responsive, hover states, image aspect ratio",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Content Components",
    taskType: "Card (complex — tags, date, author, multiple CTAs)",
    lowHours: 8,
    highHours: 12,
    notes: "Metadata, badge overlays, multi-action",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Content Components",
    taskType: "Card grid / listing layout",
    lowHours: 4,
    highHours: 8,
    notes: "Responsive grid, load more / pagination",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Content Components",
    taskType: "Carousel / slider",
    lowHours: 8,
    highHours: 16,
    notes: "Touch/swipe, dots/arrows, autoplay, a11y",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Content Components",
    taskType: "Accordion / collapsible",
    lowHours: 4,
    highHours: 8,
    notes: "Expand/collapse, animation, multi-open vs single",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Content Components",
    taskType: "Tabs",
    lowHours: 4,
    highHours: 8,
    notes: "Responsive (tabs → accordion on mobile), keyboard nav",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Content Components",
    taskType: "Modal / dialog",
    lowHours: 4,
    highHours: 8,
    notes: "Focus trap, backdrop, close on escape, a11y",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Content Components",
    taskType: "Table (responsive)",
    lowHours: 4,
    highHours: 8,
    notes: "Horizontal scroll, stacked on mobile, sortable headers",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Content Components",
    taskType: "CTA banner / callout",
    lowHours: 4,
    highHours: 6,
    notes: "Background color/image, text, button(s)",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Content Components",
    taskType: "Testimonial / quote block",
    lowHours: 4,
    highHours: 6,
    notes: "Attribution, avatar, quote styling",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Content Components",
    taskType: "Statistics / counter block",
    lowHours: 4,
    highHours: 8,
    notes: "Animated counters, grid layout",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Content Components",
    taskType: "Timeline",
    lowHours: 8,
    highHours: 16,
    notes: "Vertical/horizontal, responsive, milestone markers",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Content Components",
    taskType: "Map embed (Google/Leaflet)",
    lowHours: 4,
    highHours: 8,
    notes: "Responsive iframe or interactive map",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Content Components",
    taskType: "Social media feed embed",
    lowHours: 4,
    highHours: 8,
    notes: "Twitter/Instagram/LinkedIn embed, responsive",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Content Components",
    taskType: "Video embed (YouTube/Vimeo)",
    lowHours: 4,
    highHours: 6,
    notes: "Responsive 16:9, lazy load, thumbnail fallback",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Content Components",
    taskType: "Image gallery / lightbox",
    lowHours: 8,
    highHours: 16,
    notes: "Grid layout, lightbox viewer, touch gestures",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Content Components",
    taskType: "FAQ section",
    lowHours: 4,
    highHours: 8,
    notes: "Accordion-based, schema markup",
  },

  // --- Frontend: Form Components ---
  {
    techStack: "DRUPAL",
    category: "Frontend: Form Components",
    taskType: "Contact form (basic)",
    lowHours: 4,
    highHours: 8,
    notes: "Name, email, message, validation, submit",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Form Components",
    taskType: "Multi-step form",
    lowHours: 12,
    highHours: 24,
    notes: "Step indicator, validation per step, summary",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Form Components",
    taskType: "Newsletter signup",
    lowHours: 2,
    highHours: 4,
    notes: "Email input, submit, success/error states",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Form Components",
    taskType: "Search filters / faceted search UI",
    lowHours: 8,
    highHours: 16,
    notes: "Checkboxes, range sliders, active filter tags, clear all",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Form Components",
    taskType: "File upload component",
    lowHours: 4,
    highHours: 8,
    notes: "Drag & drop, progress bar, file type validation",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Form Components",
    taskType: "Date picker",
    lowHours: 4,
    highHours: 8,
    notes: "Calendar widget, range selection, a11y",
  },

  // --- Frontend: Page Templates ---
  {
    techStack: "DRUPAL",
    category: "Frontend: Page Templates",
    taskType: "Homepage",
    lowHours: 16,
    highHours: 32,
    notes: "Assembly of multiple components, unique layout",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Page Templates",
    taskType: "Landing page (flexible/builder)",
    lowHours: 12,
    highHours: 24,
    notes: "Component-based assembly, layout variations",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Page Templates",
    taskType: "Article / blog detail",
    lowHours: 8,
    highHours: 16,
    notes: "Long-form content, sidebar, related articles",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Page Templates",
    taskType: "Listing page (archive/index)",
    lowHours: 8,
    highHours: 16,
    notes: "Filters, pagination, card grid",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Page Templates",
    taskType: "Detail page (generic)",
    lowHours: 8,
    highHours: 12,
    notes: "Content region, sidebar, metadata",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Page Templates",
    taskType: "Search results page",
    lowHours: 8,
    highHours: 16,
    notes: "Result cards, facets, pagination, empty state",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Page Templates",
    taskType: "Error pages (404, 500)",
    lowHours: 4,
    highHours: 6,
    notes: "Branded, helpful navigation",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Page Templates",
    taskType: "User dashboard / profile",
    lowHours: 12,
    highHours: 24,
    notes: "Tabs, data tables, action buttons",
  },

  // --- Frontend: Decoupled / Headless Frontend Overhead ---
  {
    techStack: "DRUPAL",
    category: "Frontend: Decoupled / Headless Overhead",
    taskType: "SSR/SSG setup (Next.js/Nuxt)",
    lowHours: 16,
    highHours: 32,
    notes: "Routing, data fetching, build config",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Decoupled / Headless Overhead",
    taskType: "API integration layer",
    lowHours: 16,
    highHours: 40,
    notes: "REST/GraphQL client, caching, error handling",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Decoupled / Headless Overhead",
    taskType: "Preview mode (draft content) — frontend",
    lowHours: 12,
    highHours: 24,
    notes: "Authenticated preview, draft rendering",
  },
  {
    techStack: "DRUPAL",
    category: "Frontend: Decoupled / Headless Overhead",
    taskType: "Auth flow (frontend)",
    lowHours: 8,
    highHours: 16,
    notes: "Login/logout, token management, protected routes",
  },
];

async function main() {
  console.log(`Seeding ${benchmarks.length} benchmark entries...`);

  for (const benchmark of benchmarks) {
    await prisma.benchmark.upsert({
      where: {
        // Use a composite unique key based on techStack + category + taskType
        // Since schema has no unique constraint on these, we find-or-create via create+update
        // Prisma upsert requires a unique where — use a generated stable id approach via findFirst
        id: (
          await prisma.benchmark.findFirst({
            where: {
              techStack: benchmark.techStack,
              category: benchmark.category,
              taskType: benchmark.taskType,
            },
            select: { id: true },
          })
        )?.id ?? "non-existent-id",
      },
      update: {
        lowHours: benchmark.lowHours,
        highHours: benchmark.highHours,
        notes: benchmark.notes,
      },
      create: {
        techStack: benchmark.techStack,
        category: benchmark.category,
        taskType: benchmark.taskType,
        lowHours: benchmark.lowHours,
        highHours: benchmark.highHours,
        notes: benchmark.notes,
      },
    });
  }

  console.log("Benchmark seeding complete.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
