import { mkdir } from "fs/promises";
import path from "path";

export interface PhaseConfig {
  engagementId: string;
  phase: number;
  techStack: string;
  tools: string[];
  maxTurns: number;
  systemPrompt: string;
  userPrompt: string;
}

export interface ProgressEvent {
  type: "progress" | "complete" | "error";
  tool?: string;
  message?: string;
  content?: string;
}

export async function prepareWorkDir(engagementId: string): Promise<string> {
  const baseDir = path.join("/data/engagements", engagementId);

  const subdirs = [
    baseDir,
    path.join(baseDir, "tor"),
    path.join(baseDir, "research"),
    path.join(baseDir, "initial_questions"),
    path.join(baseDir, "responses_qna"),
    path.join(baseDir, "estimates"),
    path.join(baseDir, "claude-artefacts"),
  ];

  for (const dir of subdirs) {
    await mkdir(dir, { recursive: true });
  }

  return baseDir;
}

// Placeholder content per phase for the stub — replaced when Claude Agent SDK is integrated
const STUB_CONTENT: Record<number, string> = {
  0: `## Customer Research

### Organisation Profile

*Placeholder — real research will be generated by the AI agent.*

This phase analyses the TOR document, researches the customer's digital presence, audits the existing site (if applicable), and identifies hidden scope items.

### Tech Stack

| Layer | Technology |
|-------|-----------|
| CMS | TBD |
| Hosting | TBD |

### Integrations Found

- *No integrations discovered yet*

### Next Steps

Review this placeholder and re-run with a real TOR document for full research output.
`,
  1: `## TOR Assessment

### Requirement Coverage

*Placeholder — real analysis will be generated by the AI agent.*

This phase parses the TOR document, assesses each requirement for clarity, and generates structured clarifying questions.

| Area | Count | Clarity |
|------|-------|---------|
| *Pending analysis* | — | — |

### Clarifying Questions

1. *Questions will be generated after TOR analysis*

### Next Steps

Upload a TOR document to \`tor/\` and re-run this phase.
`,
  2: `## Optimistic Estimate

### Backend Tab

*Placeholder — real estimates will be generated by the AI agent.*

| Task | Conf | Low Hrs | High Hrs |
|------|------|---------|---------|
| Discovery & Architecture | — | — | — |
| Environment Setup | — | — | — |

### Assumptions

- *Assumptions will be derived from TOR analysis*

### Next Steps

Complete Phase 1 (TOR Analysis) first, then run estimation.
`,
};

export async function* runPhase(
  config: PhaseConfig
): AsyncGenerator<ProgressEvent> {
  // Stub implementation — real Claude Agent SDK integration added later
  yield {
    type: "progress",
    message: `Starting phase ${config.phase} for engagement ${config.engagementId}`,
  };

  yield {
    type: "progress",
    tool: "Read",
    message: "Reading TOR document...",
  };

  yield {
    type: "progress",
    tool: "Write",
    message: "Writing analysis output...",
  };

  const content =
    STUB_CONTENT[config.phase] ??
    `## Phase ${config.phase} Output\n\n*Placeholder — real content will be generated by the AI agent.*\n\nThis phase completed successfully in stub mode. Integrate the Claude Agent SDK to produce real artefacts.\n`;

  yield {
    type: "complete",
    content,
  };
}
